MC-12530: added documentation for serviceaccounts
cloudops/cloudmc-api-docs pull request #228
Opened 2020-09-25 14:58 UTC by katrinapoulin

### Fixes [MC-12530](https://cloud-ops.atlassian.net/browse/MC-12530)

#### Changes made
-added a ServiceAccounts page in kubernetes and kubernetes_extension

#### Related PRs
- [#189](https://github.com/cloudops/cloudmc-kubernetes-sdk/pull/189)

2020-09-25 15:29 UTC, danielvanacker reviewed
Made some comments, not sure if they're required but worth testing I think

2020-09-25 15:29 UTC, danielvanacker commented on source/includes/kubernetes_extension/_k8_serviceaccounts.md
> +   "https://cloudmc_endpoint/v1/services/a_service/an_environment/serviceaccounts"
should there be a cluster_id parameter? I.e. "?cluster_id=a_cluster_id"
similar to the other GET calls in kubernetes_extension

2020-09-25 15:29 UTC, danielvanacker commented on source/includes/kubernetes_extension/_k8_serviceaccounts.md
> +<code>GET /services/<a href="#administration-service-connections">:service_code</a>/<a href="#administration-environments">:environment_name</a>/serviceaccounts</code>
Same thing here, "?cluster_id=:cluster_id"

2020-09-25 18:01 UTC, m-orfanos requested changes

2020-09-25 18:01 UTC, m-orfanos commented on source/includes/kubernetes_extension/_k8_serviceaccounts.md
> +#### List service accounts
The files under `kubernetes_extension` must have an additional level of nesting. Navigate to the GCP plugin, k8s section then compare it to the standalone plugin.

2020-09-25 19:32 UTC, m-orfanos approved these changes
nice ⚡

2020-09-28 13:20 UTC, danielvanacker approved these changes

2020-09-28 17:29 UTC, Shabirmean approved these changes

2020-09-28 18:02 UTC, merged