MC-13839 Add api docs
cloudops/cloudmc-api-docs pull request #349
Opened 2021-04-05 18:16 UTC by razine-bensari

### Fixes [MC-13839](https://cloud-ops.atlassian.net/browse/MC-13839)

2021-04-05 18:16 UTC, razine-bensari commented
To be merged after the feature branch

2021-04-05 19:30 UTC, aaronalmeida commented on source/includes/stackpath/_delivery_rules.md
> +`id`<br/>*UUID* | A deliveryrule's unique identifier.
space between `delivery` and `rule`

2021-04-05 19:31 UTC, aaronalmeida approved these changes

2021-04-06 13:01 UTC, ehudon requested changes
Just change the typo @aaronalmeida suggested.

2021-04-06 17:00 UTC, ehudon approved these changes

2021-04-07 15:28 UTC, merged