gcp_firewall_rules API docs - MC 9247
cloudops/cloudmc-api-docs pull request #49
Opened 2019-06-12 21:22 UTC by hg-alan

API docs from doc-day for MC 9247

https://cloud-ops.atlassian.net/secure/RapidBoard.jspa?rapidView=40&modal=detail&selectedIssue=MC-9247&assignee=5cd0509a5c99a60dcbae0303

2019-06-13 19:12 UTC, pdube commented on source/includes/gcp/_list_firewall_rules.md
> +Retrieve a list of all instances in a given [environment](#administration-environments)
References to `instances` here and in the comment above

2019-06-13 19:12 UTC, pdube commented on source/includes/gcp/_list_firewall_rules.md
> +`name`<br/>*string* | Name of the resource; provided by the client when the resource is created. The name must be 1-63 characters long, and comply with RFC1035. Specifically, the name must be 1-63 ch
Should it be \`a-z\` instead of \`a-z?

2019-06-13 19:13 UTC, SeventhOfNine commented on source/includes/gcp/_list_firewall_rules.md
> +<code>GET /services/<a href="#administration-service-connections">:service_code</a>/<a href="#administration-environments">:environment_name</a>/instances</code>
replace 'instances' for 'firewallrules' so the GET line represents the call to make to the API.

2019-06-13 19:13 UTC, SeventhOfNine commented on source/includes/gcp/_list_firewall_rules.md
> +Retrieve a list of all instances in a given [environment](#administration-environments)
`Retrieve a list of all firewall rules in a given [environment](#administration-environments)`

2019-06-13 19:16 UTC, SeventhOfNine commented on source/includes/gcp/_list_firewall_rules.md
> +`name`<br/>*string* | Name of the resource; provided by the client when the resource is created. The name must be 1-63 characters long, and comply with RFC1035. Specifically, the name must be 1-63 ch
The regular expression is causing issues with formatting. I would remove the bit of the sentence 'and match ...' until the full stop.

2019-06-13 19:17 UTC, SeventhOfNine commented on source/includes/gcp/_list_firewall_rules.md
> +`sourceRanges`<br/>*list<string>* | [Output Only] Server-defined URL for the resource.
We usually say *Array[string]* for a list of strings.
Remove `[Output Only]`, this is from the GCP doc for their REST API.

2019-06-13 19:19 UTC, SeventhOfNine commented on source/includes/gcp/_list_firewall_rules.md
> +`allowed`<br/>*list<allowed>* | The list of ALLOW rules specified by this firewall. Each rule specifies a protocol and port-range tuple that describes a permitted connection.
This is an *Array[object]* not a list<allowed>

2019-06-13 19:19 UTC, SeventhOfNine commented on source/includes/gcp/_list_firewall_rules.md
> +`logConfig`<br/>*FirewallLogConfig* | This field denotes the logging options for a particular firewall rule. If logging is enabled, logs will be exported to Stackdriver.
This is an *object*

2019-06-13 19:20 UTC, SeventhOfNine commented on source/includes/gcp/_list_firewall_rules.md
> +`id`<br/>*string* | [Output Only] The unique identifier for the resource. This identifier is defined by the server.
Remove `[Output Only]`

2019-06-13 19:20 UTC, SeventhOfNine commented on source/includes/gcp/_list_firewall_rules.md
> +`recordCount`<br/>*integer* | Number of firewall rules returned.
This can be omitted.

2019-06-13 19:21 UTC, SeventhOfNine requested changes
A few updates to do. See my comments.

2019-06-13 20:45 UTC, SeventhOfNine approved these changes
LGTM

2019-06-14 14:14 UTC, hg-alan commented
*Merge approved by Simon and Flo

2019-06-14 14:14 UTC, merged